### ISSUE TITLE
stats.py crashes when --stats variable is not one of the preexisting stats.   

### ISSUE THREAD

**Issue by bkraft4257** [bkraft4257/labels#1]
stats.py crashes when --stats variable is not one of the preexisting stats.  User interface should be changed to only allow user to choose from the list of stats.

Working Example:

 ../labelSrc/stats.py 9mo.label.gwm.nii.gz -v --stats volume

Bug when stats is entered as nvoxels is at the end of this issue.  List of available stats is those in the header of the data frame ( volume  com_x  com_y  com_z com_in bb_dx bb_dy bb_dz  bb_dmin  bb_volume fill_factor).  It would be helpful to create 4 possible entries (volume, com, bb, and all).  It doesn't make a lot of sense to only report the com_x.  

Output of example that failed. 

➜  data git:(master) ✗ ../labelSrc/stats.py 9mo.label.gwm.nii.gz -v --stats nvoxels
Traceback (most recent call last):
  File "../labelSrc/stats.py", line 120, in <module>
    df_verbose = df_verbose[ stats_list ] 
  File "/Applications/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 1991, in __getitem__
    return self._getitem_array(key)
  File "/Applications/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 2035, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/Applications/anaconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1214, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['nvoxels'] not in index"

**Comment by borntoleave** [comment]
The stats.py (on branch **testKnownVolume**) is now updated with the following:

- Allows --stats tag of (**volume** com_x com_y com_z com_in bb_dx bb_dy bb_dz bb_dmin bb_volume fill_factor, **com, bb, all**).
- Added input check and will print out wrong options not in the list. Show proper error message and exit gracefully. 
- the script is wrapped into a main() function. May consider to add function arguments along with command line arguments.

**Comment by bkraft4257** [comment]
Email excerpt describing testing

The updated label package is available on the branch testKnownVolume.
In your terminal, try:
git fetch --all
git checkout testKnowVolume

in pkg/labelSrc/, the stats.py has been modified to check wrong stat entries. 
try:
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats
./stats.py ../data/9mo.label.gwm.nii.gz -v 
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats all
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats com
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats com_x bb_dy
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats bb
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats volume bb
./stats.py ../data/9mo.label.gwm.nii.gz -v --stats com some wrong input bb

in pkg/tests/, there's a genROI.py that generates a region of interest on user's input of (center1, radius1, shape1, center2, radius2, shape2). 
try:
./genROI.py
Everytime it runs, it will generate a random cube and sphere and display the shape. You can rotate the image, and click the close button to continue (this display window can be muted). It also does some simple statistics on the volume and center of mass for later tests' assertion.

There's another test_stats.py that can be automatically captured by pytest. I'm putting the test_stats in a TestLabelClass, and other future tests can be added to the class. To make the test more convincing, you can run it multiple times.
try:
py.test --count=5 -v
It will run test on the stats.py for 5 times. Every time the input ROI will be randomly generated by genROI, and its Volume and COM are compared with the results from stats.py. The test3Dcubes.nii.gz is a temporary image file generated for each shape, and can be opened by your softwares.

Please try these tests and add your problems or requirements to those functions. 

On the Github wiki, I added a sider bar that shows the hierarchy structure of the documentation pages. You can link future pages by editing that page. 

Thanks!
